import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/globe.svg" }, { url: "/dogs.svg" }],
    apple: [{ url: "/window.svg" }],
  },
};